var locale = window["locale"] = {
  'locale': 'en',
  'extensionDecription': 'Control vk.com audioplayer form any tab',
  'headerHotkeys': 'Hotkeys',
  'hotkeysHint': '',
  'labelHotkeyPlayPause': 'Play/pause',
  'labelHotkeyNextTrack': 'Next track',
  'labelHotkeyPrevTrack': 'Previous track',
  'labelHotkeyVolUp': 'Volume up',
  'labelHotkeyVolDown': 'Volume down',
  'labelHotkeyRepeat': 'Toggle repeat',
  'labelClickHereHotkey': 'Click here and press your hotkey',
  'saveHotkeys': 'Save hotkeys',
  'labelAddSong': 'Add to my music',
  'headerDblClick': 'Double click action',
  'labelToggleRepeat': 'Toggle repeat',
  'labelPlayNext': 'Play next track',
  'labelPlayPrev': 'Play previous track',
  'labelFocusPlayerTab': 'Open player tab',
  'headerButtonBadge': 'Button badge',
  'labelShowTime': 'Show track time'
};
